# Site file to deploy configure my various workstations and servers
---

- name: Apply my personal config and install packages I use frequently for workstations
  hosts: desktop
  become: yes
  become_method: sudo


  roles:
    - { role: 'ubuntu_desktop', when: ansible_distribution == 'Ubuntu' }
