
- name: Install Packages
  pacman: name={{ item }} state=latest update_cache=yes
  with_items:
    - '{{ pacman_packages }}'

- name: Grab Tarballs for pacaur
  unarchive: copy=no src={{ item }} dest=/tmp owner=ben
  with_items:
    - '{{ pacaur_tarballs }}' 

- name: Run pacaur install script
  script: files/pacaur_install.sh
  become: yes
  become_user: ben

#There is not yet a pacaur module.. might have to fix that

- name: Install Aur packages
  command: /usr/bin/pacaur -S  --noconfirm --noedit  '{{ pacaur_packages }}' 
  ignore_errors: yes

- name: Enable Services 
  service: name={{ item }} enabled=yes
  with_items:
    - '{{ services}}'


