
- name: Add PPAs for packages I use frequently
  apt_repository: repo={{ item }} state=present update_cache=yes
  with_items:
    - '{{ ppas }}'


- name: Install Packages
  package: name={{ item }} state=latest
  with_items:
    - '{{ packages }}'

